This works BUT sometimes gives the following (?): NoMethodError:     undefined method `+' for nil:NilClass     # /Users/mattiagiuffrida/.rvm/gems/ruby-2.5.1/gems/connection_pool-2.2.2/lib/connection_pool.rb:89:in `checkout'     # /Users/mattiagiuffrida/.rvm/gems/ruby-2.5.1/gems/connection_pool-2.2.2/lib/connection_pool.rb:62:in `block in with'     # /Users/mattiagiuffrida/.rvm/gems/ruby-2.5.1/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'     # /Users/mattiagiuffrida/.rvm/gems/ruby-2.5.1/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'     # ./lib/faraday/adapter/patron.rb:19:in `call'     # ./lib/faraday/response.rb:11:in `call'     # ./lib/faraday/request/url_encoded.rb:23:in `call'     # ./lib/faraday/request/multipart.rb:25:in `call'     # ./lib/faraday/rack_builder.rb:153:in `build_response'     # ./lib/faraday/connection.rb:504:in `run_request'     # ./lib/faraday/connection.rb:233:in `options'     # ./spec/support/shared_examples/request_method.rb:94:in `public_send'     # ./spec/support/shared_examples/request_method.rb:94:in `block (2 levels) in <top (required)>'